print('Guess the number!')
print('Enter the limit: 10')
print('Im thinking of a number from 1 to 10')
print('Your guess: 5')
print('Too low')
print('Your guess: 7')
print('Too low')
print('Your guess: 9')
print('Too low')
print('Your guess: 10')
print('You guess it in 4 tries.')
print('Would you like to play again?')
print('y/n')
print('y')
print('Im thinking of a number from 1 to to')
print('Your guess: 20')
print('Too high')
print('Your guess: 10')
print('Too low')
print('Your guess: 15')
print('You guess it in 3 tries')
print('Would you like to play again?')
print('y/n')
print('n')
print('Bye!')

